/**
 * HTTP error-envelope codes
 */
export enum ApiErrorCode {
  // Status-mapped (assigned by BadResponseFilter from the HTTP status)
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  // Validation (validationPipe)
  VALIDATION_ERROR = "VALIDATION_ERROR",
  // Two-factor auth
  TOTP_LOCKED = "TOTP_LOCKED",
  TOTP_INVALID = "TOTP_INVALID",
}

/**
 * Task-payload error codes
 */
export enum TaskErrorCode {
  TASK_ERROR = "TASK_ERROR",
  JAVA_INSTALL_ERROR = "JAVA_INSTALL_ERROR",
  SERVER_CREATE_ERROR = "SERVER_CREATE_ERROR",
  SERVER_DUPLICATE_ERROR = "SERVER_DUPLICATE_ERROR",
  SERVER_IMPORT_ERROR = "SERVER_IMPORT_ERROR",
  CONTENT_INSTALL_FAILED = "CONTENT_INSTALL_FAILED",
  CONTENT_UPDATE_FAILED = "CONTENT_UPDATE_FAILED",
  CONTENT_REMOVE_FAILED = "CONTENT_REMOVE_FAILED",
}
