import type { IConfiguration } from "@/core/types/config";
import {
  ServerStatus,
  type IServer,
  type ServerCoreType,
} from "@shared/types/server/server.types";
import { UserPermissions, type IUser } from "@shared/types/user.types";
import { CORE_TYPES } from "./legacy-core-types";
import type { LegacyConfig, LegacyServer, LegacyUser } from "./legacy.types";

// Legacy permission -> new permissions. Unmapped ones are dropped
const PERMISSION_MAP: Record<string, UserPermissions[]> = {
  accounts: [UserPermissions.ACCOUNTS_MANAGEMENT],
  file_manager: [UserPermissions.FILE_MANAGER],
  manage_servers: [
    UserPermissions.SERVERS_CONTROL,
    UserPermissions.SERVERS_CONFIGURE,
  ],
  making_servers: [UserPermissions.CREATE_SERVERS],
  monitor_servers: [UserPermissions.SERVERS_VIEW],
  manage_java: [UserPermissions.MANAGE_JAVA],
  manage_plugins: [UserPermissions.MANAGE_PLUGINS],
  system_monitoring: [UserPermissions.SYSTEM_MONITORING],
  kubek_settings: [UserPermissions.KUBEK_SETTINGS],
};

// New permissions with no legacy equivalent, granted to admins only
const ADMIN_ONLY_PERMISSIONS: UserPermissions[] = [
  UserPermissions.BACKUPS,
  UserPermissions.SCHEDULER_MANAGEMENT,
  UserPermissions.AUDIT_LOG,
];

// Admin = could manage both accounts and settings in the old panel
export function mapPermissions(legacy: string[] = []): {
  permissions: UserPermissions[];
  isAdmin: boolean;
} {
  const set = new Set<UserPermissions>();
  for (const perm of legacy) {
    for (const mapped of PERMISSION_MAP[perm] ?? []) set.add(mapped);
  }

  const isAdmin =
    legacy.includes("accounts") && legacy.includes("kubek_settings");
  if (isAdmin) for (const perm of ADMIN_ONLY_PERMISSIONS) set.add(perm);

  return { permissions: [...set], isAdmin };
}

export function mapConfig(legacy: LegacyConfig): Partial<IConfiguration> {
  return {
    eulaAccepted: !!legacy.eulaAccepted,
    authorization: !!legacy.authorization,
    port:
      typeof legacy.webserverPort === "number" ? legacy.webserverPort : 8000,
    ftpd: {
      enabled: !!legacy.ftpd?.enabled,
      username: legacy.ftpd?.username,
      password: legacy.ftpd?.password,
      port: legacy.ftpd?.port,
    },
    subnetsAccessRestriction: {
      enabled: !!legacy.allowOnlyIPsList,
      subnets: legacy.IPsAllowed ?? [],
    },
    telegramBot: {
      enabled: !!legacy.telegramBot?.enabled,
      token: legacy.telegramBot?.token,
      chatIds: (legacy.telegramBot?.chatIds ?? []).map(String),
    },
  };
}

// The legacy version not stored the core, so ill try guess it from jar name
function inferCoreType(binaryName: string): ServerCoreType {
  const name = binaryName.toLowerCase();
  for (const core of Object.values(CORE_TYPES)) {
    if (name.includes(core)) return core;
  }
  return "custom";
}

// Map a legacy server onto a bundled blueprint id
function inferBlueprintId(
  isBedrock: boolean,
  coreType: ServerCoreType,
): string {
  if (isBedrock) return "com.kubek.bedrock";
  if (coreType === "custom") return "com.kubek.custom";
  return `com.kubek.${coreType}`;
}

function parseXmx(args: string[]): number | undefined {
  for (const arg of args) {
    const match = /-Xmx(\d+)([mMgG]?)/.exec(arg);
    if (match) {
      const value = parseInt(match[1], 10);
      return match[2]?.toLowerCase() === "g" ? value * 1024 : value;
    }
  }
  return undefined;
}

// binaryName is the jar found on disk, empty for Bedrock or when none exists
export function mapServer(
  legacy: LegacyServer,
  name: string,
  binaryName: string,
  startupArguments: string[],
): Omit<IServer, "id"> {
  const isBedrock = legacy.minecraftType === "bedrock";
  const coreType: ServerCoreType = isBedrock
    ? "custom"
    : inferCoreType(binaryName);
  return {
    name,
    status: ServerStatus.STOPPED,
    restartOnError: {
      enabled: !!legacy.restartOnError,
      attempts:
        typeof legacy.maxRestartAttempts === "number"
          ? legacy.maxRestartAttempts
          : 3,
    },
    folderId: null,
    // blueprint assignment for servers imported from old Kubek versions
    blueprintId: inferBlueprintId(isBedrock, coreType),
    blueprintVersion: "1.0.0",
    runtimeKind: "native",
    variables: { XMX: parseXmx(startupArguments) ?? 2048 },
  };
}

// hashedPassword is NEW, generated by the caller
// serverNameToId remaps the old serversAllowed names to the new UUIDs
export function mapUser(
  legacy: LegacyUser,
  username: string,
  id: string,
  hashedPassword: string,
  serverNameToId: Map<string, string>,
): IUser {
  const { permissions, isAdmin } = mapPermissions(legacy.permissions ?? []);
  const allowed = (legacy.serversAllowed ?? [])
    .map((name) => serverNameToId.get(name))
    .filter((mappedId): mappedId is string => !!mappedId);

  return {
    id,
    username,
    password: hashedPassword,
    secret: "",
    permissions,
    serversRestrict: {
      enabled: !!legacy.serversAccessRestricted,
      allowed,
    },
    isAdmin,
  };
}
